// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4owhS3gao8xzJpbh9L3fFxJ3MO1-obC4',
    appId: '1:597207098201:web:022f7a08208755ee3d2248',
    messagingSenderId: '597207098201',
    projectId: 'devathon786-f8ccd',
    authDomain: 'devathon786-f8ccd.firebaseapp.com',
    storageBucket: 'devathon786-f8ccd.appspot.com',
    measurementId: 'G-Z9RS002BT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp0qSsrVM4h6glYUCH6meobTO8-fF9Wk4',
    appId: '1:597207098201:android:760fefe1f481e7153d2248',
    messagingSenderId: '597207098201',
    projectId: 'devathon786-f8ccd',
    storageBucket: 'devathon786-f8ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAvB-HCC3MaGtGwlnioU1goamoAhx5kWk',
    appId: '1:597207098201:ios:eb251ccd1a7fe0a03d2248',
    messagingSenderId: '597207098201',
    projectId: 'devathon786-f8ccd',
    storageBucket: 'devathon786-f8ccd.appspot.com',
    iosBundleId: 'com.example.devathonSmitFlutter',
  );
}
